In [8]:
import pymongo
import pandas as pd

In [9]:
conn = pymongo.MongoClient('localhost', 27017)

In [3]:
print(conn.list_database_names())

['DA', 'admin', 'config', 'da_design_20171472', 'local']

In [4]:
db = conn['DA']

In [5]:
print(db.list_collection_names())

['total', 'pop', 'balad', 'hip-hop', 'R&B', 'k-pop']

In [6]:
'pop' in db.list_collection_names()

True

In [7]:
for r in db['pop'].find({}):
    print(r)

{'_id': ObjectId('60affb8e6e02e71aa69659f4'), '': 0, 'song': 'Maroon 5  - Sugar (Official Music Video)-09R8_2nJtjg.mp3', 'genre': 'pop', 'singer': 'Maroon 5', 'title': 'Sugar', 'tempo1': 0.7239187158466347, 'tempo2': 0.7035928556587647, 'mean_ft1': 0.2793587246232398, 'var_ft1': 0.3095489828113067, 'mean_ft2': 0.28554458003565425, 'var_ft2': 0.4616086430699478, 'mean_mel1': 0.0, 'var_mel1': 0.5858037396996643, 'mean_mel2': 0.02217905738354553, 'var_mel2': 1.0, 'mean_harm1': 0.2767517312958054, 'var_harm1': 0.27676242909235915, 'mean_perc1': 0.2767497976256125, 'var_perc1': 0.2767724758693299, 'mean_harm2': 0.2767499027111383, 'var_harm2': 0.2768647886547181, 'mean_perc2': 0.2767496612631276, 'var_perc2': 0.2768259983479497, 'mean_sc1': 0.2775952683185812, 'var_sc1': 0.27682950066549417, 'mean_sc2': 0.2778439483511129, 'var_sc2': 0.2768154216470932, 'mean_chroma1': 0.2783586299848917, 'var_chroma1': 0.2770669755204456, 'mean_chroma2': 0.2781337956755621, 'var_chroma2': 0.2770876701860049, 'mean_mfccs1': 0.2786674345352791, 'var_mfccs1': 0.2768289633506477, 'mean_mfccs2': 0.27862586400879896, 'var_mfccs2': 0.2768440852840917, 'zero_crossings_mean1': 0.2770421733739382, 'zero_crossings_var1': 0.2770186500207113, 'zero_crossings_mean2': 0.2771222506953204, 'zero_crossings_var2': 0.2770840777318112}
{'_id': ObjectId('60affb8e6e02e71aa69659f5'), '': 1, 'song': 'Carly Rae Jepsen  - Call Me Maybe-fWNaR-rxAic.mp3', 'genre': 'pop', 'singer': 'Carly Rae Jepsen', 'title': 'Call Me Maybe', 'tempo1': 0.8514156228514809, 'tempo2': 0.8514156228514809, 'mean_ft1': 0.3327477141285691, 'var_ft1': 0.3707649867353653, 'mean_ft2': 0.3332482199592572, 'var_ft2': 0.3751713587710398, 'mean_mel1': 0.0, 'var_mel1': 0.950454139998032, 'mean_mel2': 0.003389609660345128, 'var_mel2': 1.0, 'mean_harm1': 0.3287572660569488, 'var_harm1': 0.3287824871294422, 'mean_perc1': 0.32875750620100924, 'var_perc1': 0.32877481918207435, 'mean_harm2': 0.3287572901279873, 'var_harm2': 0.3287836275341694, 'mean_perc2': 0.3287574404667192, 'var_perc2': 0.3287789985435037, 'mean_sc1': 0.3303342691114658, 'var_sc1': 0.3288771117814216, 'mean_sc2': 0.3303896540583364, 'var_sc2': 0.3288966739948091, 'mean_chroma1': 0.3304830595066514, 'var_chroma1': 0.3291738178791054, 'mean_chroma2': 0.33061905330447305, 'var_chroma2': 0.32915137028033875, 'mean_mfccs1': 0.33101750599872404, 'var_mfccs1': 0.32887482247484723, 'mean_mfccs2': 0.3308741743426093, 'var_mfccs2': 0.3288761029547253, 'zero_crossings_mean1': 0.3292401068275419, 'zero_crossings_var1': 0.32918771669471264, 'zero_crossings_mean2': 0.3293066872206008, 'zero_crossings_var2': 0.3292388522986186}
{'_id': ObjectId('60affb8e6e02e71aa69659f6'), '': 2, 'song': 'Sia  - Chandelier (Official Video)-2vjPBrBU-TM.mp3', 'genre': 'pop', 'singer': 'Sia', 'title': 'Chandelier', 'tempo1': 0.5962621091102221, 'tempo2': 0.4981887415903044, 'mean_ft1': 0.2337497087882243, 'var_ft1': 0.3432900924856588, 'mean_ft2': 0.2381950220536183, 'var_ft2': 0.4594042781757128, 'mean_mel1': 0.0, 'var_mel1': 0.7521995148970828, 'mean_mel2': 0.019198882855249542, 'var_mel2': 1.0, 'mean_harm1': 0.2284870129688485, 'var_harm1': 0.22858943405156376, 'mean_perc1': 0.228487431499972, 'var_perc1': 0.22850979630738716, 'mean_harm2': 0.2284869975552299, 'var_harm2': 0.22870160546549495, 'mean_perc2': 0.2284869729403297, 'var_perc2': 0.2285308799765133, 'mean_sc1': 0.22924332398104136, 'var_sc1': 0.2285350113270445, 'mean_sc2': 0.229393700321818, 'var_sc2': 0.22852684020675185, 'mean_chroma1': 0.22951236384729676, 'var_chroma1': 0.2287822723843506, 'mean_chroma2': 0.229638071918636, 'var_chroma2': 0.2287531599553421, 'mean_mfccs1': 0.2302034461843864, 'var_mfccs1': 0.22859818598193546, 'mean_mfccs2': 0.2302283732793153, 'var_mfccs2': 0.2285738279866188, 'zero_crossings_mean1': 0.2287845354568216, 'zero_crossings_var1': 0.22875625945329264, 'zero_crossings_mean2': 0.22882040852802735, 'zero_crossings_var2': 0.2287849036532539}
{'_id': ObjectId('60affb8e6e02e71aa69659f7'), '': 3, 'song': 'Mark Ronson  - Uptown Funk (Official Video) ft. Bruno Mars-OPf0YbXqDm0.mp3', 'genre': 'pop', 'singer': 'Mark Ronson', 'title': 'Uptown Funk', 'tempo1': 0.8967855470389283, 'tempo2': 0.8967855470389283, 'mean_ft1': 0.35731088401612143, 'var_ft1': 0.4460724241062045, 'mean_ft2': 0.361136336788178, 'var_ft2': 0.4963943949919965, 'mean_mel1': 0.0, 'var_mel1': 0.7937441210891099, 'mean_mel2': 0.014533321646545527, 'var_mel2': 1.0, 'mean_harm1': 0.3511414428688426, 'var_harm1': 0.3511708881272125, 'mean_perc1': 0.3511426060299038, 'var_perc1': 0.35121654765628724, 'mean_harm2': 0.35114149070936, 'var_harm2': 0.3512039393140073, 'mean_perc2': 0.3511429817376444, 'var_perc2': 0.35123476402463105, 'mean_sc1': 0.3528842923221884, 'var_sc1': 0.35124889496141604, 'mean_sc2': 0.3527931856612969, 'var_sc2': 0.3512289935370773, 'mean_chroma1': 0.3532643530766178, 'var_chroma1': 0.3515943328285336, 'mean_chroma2': 0.35339454780956553, 'var_chroma2': 0.3515491945586384, 'mean_mfccs1': 0.3535353689801982, 'var_mfccs1': 0.35125684081477504, 'mean_mfccs2': 0.35354721889878704, 'var_mfccs2': 0.35124730411548494, 'zero_crossings_mean1': 0.3518551301554289, 'zero_crossings_var1': 0.3517455015673052, 'zero_crossings_mean2': 0.3518655099036108, 'zero_crossings_var2': 0.3517526691011722}
{'_id': ObjectId('60affb8e6e02e71aa69659f8'), '': 4, 'song': 'Ed Sheeran  - Shape of You (Official Music Video)-JGwWNGJdvx8.mp3', 'genre': 'pop', 'singer': 'Ed Sheeran', 'title': 'Shape of You', 'tempo1': 0.7276840939092635, 'tempo2': 0.7276840939092635, 'mean_ft1': 0.2690090713649693, 'var_ft1': 0.4335960249217325, 'mean_ft2': 0.2715104791047297, 'var_ft2': 0.5054650570923488, 'mean_mel1': 0.0, 'var_mel1': 0.9326377396715432, 'mean_mel2': 0.005177821406846361, 'var_mel2': 1.0, 'mean_harm1': 0.2626587378705955, 'var_harm1': 0.2627901907641025, 'mean_perc1': 0.2626570331133789, 'var_perc1': 0.2627131800027033, 'mean_harm2': 0.2626585543789911, 'var_harm2': 0.26282851829586623, 'mean_perc2': 0.26265775202358443, 'var_perc2': 0.26274351923578176, 'mean_sc1': 0.2636296289596313, 'var_sc1': 0.26274051784165026, 'mean_sc2': 0.2635154625599646, 'var_sc2': 0.2627380458691054, 'mean_chroma1': 0.26386525514664017, 'var_chroma1': 0.2630095862384968, 'mean_chroma2': 0.2638462602795913, 'var_chroma2': 0.26298592675213184, 'mean_mfccs1': 0.2645213278572097, 'var_mfccs1': 0.2627621012516801, 'mean_mfccs2': 0.2645750551840577, 'var_mfccs2': 0.2627451820710396, 'zero_crossings_mean1': 0.2629493097467636, 'zero_crossings_var1': 0.26292587077878843, 'zero_crossings_mean2': 0.26295376328793585, 'zero_crossings_var2': 0.2629296000287443}
{'_id': ObjectId('60affb8e6e02e71aa69659f9'), '': 5, 'song': 'Wiz Khalifa  - See You Again ft. Charlie Puth [Official Video] Furious 7 Soundtrack-RgKAFK5djSk.mp3', 'genre': 'pop', 'singer': 'Wiz Khalifa', 'title': 'See You Again ft. Charlie Puth', 'tempo1': 1.0, 'tempo2': 1.0, 'mean_ft1': 0.32466068428782485, 'var_ft1': 0.4799419282651407, 'mean_ft2': 0.32681382148438803, 'var_ft2': 0.5318771357171228, 'mean_mel1': 0.0, 'var_mel1': 0.7815390777865168, 'mean_mel2': 0.004781723863178489, 'var_mel2': 0.8532141101070827, 'mean_harm1': 0.3194961074591102, 'var_harm1': 0.3196486419993851, 'mean_perc1': 0.3194962452824692, 'var_perc1': 0.3195281650539888, 'mean_harm2': 0.3194960908975855, 'var_harm2': 0.3197076994809924, 'mean_perc2': 0.3194957623221485, 'var_perc2': 0.3195319451837909, 'mean_sc1': 0.3204083033367037, 'var_sc1': 0.3196159138322233, 'mean_sc2': 0.3208150572887965, 'var_sc2': 0.3196060224380583, 'mean_chroma1': 0.32083664756767555, 'var_chroma1': 0.3199419295899805, 'mean_chroma2': 0.3209738391881659, 'var_chroma2': 0.3199215055203853, 'mean_mfccs1': 0.3216865103308472, 'var_mfccs1': 0.3196133140627032, 'mean_mfccs2': 0.3216776614055231, 'var_mfccs2': 0.3196102971481581, 'zero_crossings_mean1': 0.3197674711555543, 'zero_crossings_var1': 0.31974997715510595, 'zero_crossings_mean2': 0.3197808829287168, 'zero_crossings_var2': 0.3197616178950056}
{'_id': ObjectId('60affb8e6e02e71aa69659fa'), '': 6, 'song': 'The Wanted  - Glad You.mp3', 'genre': 'pop', 'singer': 'The Wanted', 'title': 'Glad You', 'tempo1': 0.7025319619856433, 'tempo2': 0.7025319619856433, 'mean_ft1': 0.2571228593082901, 'var_ft1': 0.2638294590678237, 'mean_ft2': 0.2588816386387053, 'var_ft2': 0.2817409472589372, 'mean_mel1': 0.0, 'var_mel1': 0.7584885487284518, 'mean_mel2': 0.01544814230503111, 'var_mel2': 1.0, 'mean_harm1': 0.25529803071663026, 'var_harm1': 0.2553047592197876, 'mean_perc1': 0.2552979794448335, 'var_perc1': 0.2553002834924729, 'mean_harm2': 0.2552980528584595, 'var_harm2': 0.2553176066337901, 'mean_perc2': 0.2552980773342405, 'var_perc2': 0.2553060965611421, 'mean_sc1': 0.25667725985563444, 'var_sc1': 0.2553944163372415, 'mean_sc2': 0.2565327571289785, 'var_sc2': 0.2553682405288035, 'mean_chroma1': 0.2564420527943512, 'var_chroma1': 0.2556050489328669, 'mean_chroma2': 0.25674045731607553, 'var_chroma2': 0.2555968209165061, 'mean_mfccs1': 0.2571076142572668, 'var_mfccs1': 0.25539242607698115, 'mean_mfccs2': 0.2573085797572475, 'var_mfccs2': 0.2553837007880105, 'zero_crossings_mean1': 0.2557146283953785, 'zero_crossings_var1': 0.2556644891615037, 'zero_crossings_mean2': 0.255679695963674, 'zero_crossings_var2': 0.2556376125498903}
{'_id': ObjectId('60affb8e6e02e71aa69659fb'), '': 7, 'song': 'Cheryl Cole  - Fight For This Love (Official Video)-4umc87T5UMs.mp3', 'genre': 'pop', 'singer': 'Cheryl Cole', 'title': 'Fight For This Love', 'tempo1': 0.9288207051692344, 'tempo2': 0.9288207051692344, 'mean_ft1': 0.35618495694184965, 'var_ft1': 0.36383341831009536, 'mean_ft2': 0.35707527581296805, 'var_ft2': 0.3689535819777094, 'mean_mel1': 0.0, 'var_mel1': 0.7917482184555162, 'mean_mel2': 0.01139605303362673, 'var_mel2': 1.0, 'mean_harm1': 0.3539242512704296, 'var_harm1': 0.3539294567087543, 'mean_perc1': 0.35392441273106273, 'var_perc1': 0.3539297147904224, 'mean_harm2': 0.3539242193864716, 'var_harm2': 0.3539346742938696, 'mean_perc2': 0.3539243202741563, 'var_perc2': 0.3539298688281232, 'mean_sc1': 0.3555127716420285, 'var_sc1': 0.3540800528526529, 'mean_sc2': 0.3555844278124347, 'var_sc2': 0.35401277099168466, 'mean_chroma1': 0.3557763379947931, 'var_chroma1': 0.3543563235795178, 'mean_chroma2': 0.3556358275806409, 'var_chroma2': 0.3543370474884385, 'mean_mfccs1': 0.35628421312011505, 'var_mfccs1': 0.35405294789684005, 'mean_mfccs2': 0.35625394296133794, 'var_mfccs2': 0.3540332670128956, 'zero_crossings_mean1': 0.3544902534387853, 'zero_crossings_var1': 0.3544216882272436, 'zero_crossings_mean2': 0.3545111351973238, 'zero_crossings_var2': 0.3544374173684577}

In [20]:
genre = 'pop'
pd.DataFrame(list(db['R&B'].find({}))).drop(['_id', 'genre'], axis = 1)

,,mean_chroma1,mean_chroma2,mean_ft1,mean_ft2,mean_harm1,mean_harm2,mean_mel1,mean_mel2,mean_mfccs1,...,var_mfccs1,var_mfccs2,var_perc1,var_perc2,var_sc1,var_sc2,zero_crossings_mean1,zero_crossings_mean2,zero_crossings_var1,zero_crossings_var2
0,0,0.297165,0.297090,0.301484,0.305140,0.295810,0.295811,0.000000,0.010757,0.297828,...,0.295909,0.295913,0.295898,0.295920,0.295949,0.295889,0.296131,0.296185,0.296105,0.296149
1,1,0.332611,0.332970,0.334895,0.339049,0.331479,0.331479,0.001784,0.000000,0.333753,...,0.331612,0.331597,0.331486,0.331535,0.331585,NaN,0.331877,0.331858,0.331842,0.331826
2,2,0.266291,0.266421,0.272047,0.273714,0.265167,0.265167,0.000000,0.005900,0.266921,...,0.265272,0.265257,0.265216,0.265245,0.265275,NaN,0.265569,0.265513,0.265524,0.265480
3,3,0.260235,0.260219,0.264387,0.266787,0.259186,0.259186,0.000000,0.006172,0.260930,...,0.259300,0.259281,0.259214,0.259228,0.259259,NaN,0.259434,0.259437,0.259417,0.259419
4,4,0.302579,0.302873,0.307657,0.311668,0.301367,0.301367,0.000000,0.010698,0.303389,...,0.301507,0.301455,0.301405,0.301422,0.301462,NaN,0.301716,0.301660,0.301686,0.301638
5,5,0.266862,0.266918,0.267492,0.273015,0.265916,0.265916,0.000000,0.014736,0.267677,...,0.266006,0.266009,0.265920,0.265957,0.265974,NaN,0.266048,0.266088,0.266043,0.266079
6,6,0.264826,0.264960,0.269959,0.271783,0.263725,0.263725,0.000000,0.012976,0.265469,...,0.263827,0.263812,0.263787,0.263796,0.263804,NaN,0.264001,0.264032,0.263980,0.264005
7,7,0.312727,0.311855,0.310753,0.311611,0.310361,0.310361,0.000000,0.005732,0.312462,...,0.310449,0.310482,0.310362,0.310363,0.310435,NaN,0.310645,0.310621,0.310625,0.310604
8,8,0.321431,0.320982,0.321138,0.325543,0.319395,0.319395,0.000000,0.017718,0.321540,...,0.319495,0.319495,0.319421,0.319462,0.319466,NaN,0.319630,0.319591,0.319616,0.319581

In [139]:
title = 'Uptown Funk'
genre = 'hip-hop'

In [146]:
selected_song = pd.DataFrame(list(db['total'].find({'title':title}))).reset_index(drop = True).set_index('title')
selected_genre_songs = pd.DataFrame(list(db[genre].find({}))).reset_index(drop = True).set_index('title')

In [147]:
import numpy as np
selected_song = selected_song.select_dtypes([np.number])
selected_genre_songs = selected_genre_songs.select_dtypes([np.number])

In [158]:
c = pd.concat([selected_song,selected_genre_songs]).dropna(axis = 1)

In [159]:
from sklearn.metrics.pairwise import cosine_similarity
similarty = cosine_similarity(c)

In [128]:
sim_df = pd.DataFrame(similarty, index = c.index, columns = c.index)
result = sim_df['Uptown Funk'].sort_values(ascending = False).drop('Uptown Funk').to_frame()

result = pd.DataFrame(result.index)
result

                                title
0         돈 Call Me (Prod. by BRLLNT)
1            독 (Feat. E Sens of 슈프림팀)
2                            +82 Bars
3                                BAND
4   붕붕(Feat. Sik-K)(Prod. GroovyRoom)
5                 flex (Prod.By 기리보이)
6                    띵 (Prod.By 기리보이)
7                                아름다워
8    수퍼비와 (Feat. BewhY) (Prod. BewhY)
9                          First Love
10                             METEOR

In [156]:
def get_recommend(title, genre, n=5):
    conn = pymongo.MongoClient('localhost', 27017)
    db = conn['DA']
    if genre in db.list_collection_names():
        selected_song = pd.DataFrame(list(db['total'].find({'title':title}))).reset_index(drop = True).set_index('title')
        selected_genre_songs = pd.DataFrame(list(db[genre].find({}))).reset_index(drop = True).set_index('title')
        selected_song = selected_song.select_dtypes([np.number])
        selected_genre_songs = selected_genre_songs.select_dtypes([np.number])
    else: pass
    
    df = pd.concat([selected_song, selected_genre_songs], axis = 0).dropna(axis = 1)
    
    similarty = cosine_similarity(df)
    sim_df = pd.DataFrame(similarty, index = df.index, columns = df.index)
    
    result = sim_df[title].sort_values(ascending = False).drop(title).to_frame()
    
    return pd.DataFrame(result.index).head(n)

In [157]:
get_recommend(title, genre)

                               title
0        돈 Call Me (Prod. by BRLLNT)
1           독 (Feat. E Sens of 슈프림팀)
2                           +82 Bars
3                               BAND
4  붕붕(Feat. Sik-K)(Prod. GroovyRoom)

In [171]:
b = pd.read_csv('/home/ubuntu/DA/dataframe/balad_df.csv')
b_n = b.select_dtypes([np.number])
b_n

,Unnamed: 0,tempo1,tempo2,mean_ft1,var_ft1,mean_ft2,var_ft2,mean_mel1,var_mel1,mean_mel2,...,mean_chroma2,var_chroma2,mean_mfccs1,var_mfccs1,mean_mfccs2,var_mfccs2,zero_crossings_mean1,zero_crossings_var1,zero_crossings_mean2,zero_crossings_var2
0,0,0.702465,0.702465,0.308541,0.401742,0.311656,0.519327,0.0,0.688646,0.012571,...,0.305886,0.305206,0.306827,0.304981,0.306906,0.304978,0.305083,0.305070,0.305129,0.305110
1,1,0.669832,0.669832,0.302170,0.395739,0.307564,0.570422,0.0,0.638824,0.015888,...,0.299335,0.298413,0.299923,0.298184,0.300006,0.298167,0.298312,0.298297,0.298392,0.298365
2,2,0.664583,0.459114,0.245700,0.310583,0.247041,0.353630,0.0,0.780974,0.009041,...,0.243831,0.243109,0.244477,0.242933,0.244499,0.242921,0.243005,0.242996,0.242986,0.242979
3,3,0.759023,0.503499,0.249898,0.272434,0.254752,0.376615,0.0,0.824887,0.011523,...,0.249207,0.248286,0.249662,0.248080,0.249664,0.248061,0.248210,0.248194,0.248275,0.248248
4,4,0.520623,0.802143,0.242276,0.277212,0.246773,0.353780,0.0,0.760502,0.019459,...,0.240224,0.239390,0.240720,0.239196,0.240805,0.239188,0.239399,0.239372,0.239472,0.239431
5,5,1.000000,0.629920,0.262370,0.301007,0.267256,0.419801,0.0,0.661365,0.015169,...,0.260871,0.260155,0.261582,0.259952,0.261557,0.259931,0.260123,0.260100,0.260191,0.260155
6,6,0.878938,0.846274,0.292228,0.304104,0.294613,0.371602,0.0,0.846187,0.007093,...,0.291962,0.291331,0.292914,0.291095,0.292976,0.291102,0.291216,0.291203,0.291231,0.291216
7,7,0.772905,0.820135,0.302727,0.332749,0.305141,0.445472,0.0,0.890631,0.004084,...,0.301484,0.300956,0.302594,0.300717,0.302573,0.300726,0.300793,0.300784,0.300852,0.300837
8,8,0.799577,0.773925,0.287502,0.294436,0.290116,0.337061,0.0,0.727411,0.011426,...,0.287603,0.286889,0.288467,0.286661,0.288444,0.286656,0.286706,0.286700,0.286784,0.286769